spring:
  application:
    name: wallet
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/${DB_NAME}}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  flyway:
    enabled: true
    baseline-on-migrate: true


jwt:
  secret:
    key: ${SECRETKEY}
  expiration:
    time: 86400000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.results.loading: TRACE

openpay:
  sandbox:
    base-url: ${BASE_URL}
    merchant-id: ${MERCHANT_ID}
    private-key: ${PRIVATE_KEY}
